### ISSUE TITLE
another way to display info. about missing

### ISSUE THREAD

**Issue by soodoku** [njtierney/naniar#13]
One simple way to display missing data in bivariate plots is to create a separate variable for where the values are missing and to plot that information. See script and an example plot here:

https://gist.github.com/soodoku/36fecfc442342c0e01aad6742b8ee47e

**Comment by njtierney** [comment]
Thanks for this!

Sorry I haven't responded for so long, :(

Can you think of a way to automate/functionalise this process? Seems interesting!

**Comment by soodoku** [comment]
Sure --- easy enough to do. Will do a PR.

**Comment by njtierney** [comment]
OK great, I'm interested in seeing how this can be used to automate the process of adding this information to the data. This is how most of the plotting functions work in `narnia`, take `gg_missing_var`, for example. This uses the function `miss_var_summary` and then plots it.

This is so that the user can do the quick plot, but also has the data behind the plot readily available, if that makes sense?

Please also feel free to post the function code here in the issue, I don't want you doing heaps of extra work with the package. :)

**Comment by soodoku** [comment]
Perfect! Will do as you suggest: post the function here

**Comment by njtierney** [comment]
OK great! :)

**Comment by njtierney** [comment]
Hi @soodoku , how are you going with that this?

**Comment by njtierney** [comment]
Hi @soodoku I am going to close this for the moment, just trying to clean up my issues - please feel free to reopen it! :)
